// Package skill_upload_session stores the short-lived state that coordinates
// Skill uploads across Backend instances.  Redis is deliberately used only
// for coordination and a bounded result cache; the durable confirmation
// result remains in MySQL receipts.
package skill_upload_session

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"

	goredis "github.com/redis/go-redis/v9"
)

var (
	ErrNotFound       = errors.New("skill upload session not found")
	ErrOwnerMismatch  = errors.New("skill upload session owner mismatch")
	ErrConfirmRunning = errors.New("skill upload confirmation is already running")
	ErrConfirmFailed  = errors.New("skill upload confirmation has failed")
	ErrLeaseLost      = errors.New("skill upload confirmation lease lost")
)

const (
	statePending    = "pending"
	stateConfirming = "confirming"
	stateConfirmed  = "confirmed"
	stateFailed     = "failed"
)

// Session is the server-derived upload metadata.  Confirm never trusts the
// client to provide name, sizes, or hashes when a session store is enabled.
type Session struct {
	UploadID          string    `json:"upload_id"`
	State             string    `json:"state"`
	OwnerID           string    `json:"owner_id,omitempty"`
	ObjectKey         string    `json:"object_key"`
	Name              string    `json:"name"`
	Description       string    `json:"description,omitempty"`
	SHA256            string    `json:"sha256"`
	FileCount         int       `json:"file_count"`
	TotalSize         int64     `json:"total_size"`
	PackageSize       int64     `json:"package_size"`
	ConfirmedSkillID  uint      `json:"confirmed_skill_id,omitempty"`
	ConfirmLeaseUntil time.Time `json:"confirm_lease_until,omitempty"`
	ConfirmToken      string    `json:"-"`
}

type Options struct {
	TTL             time.Duration
	Lease           time.Duration
	ResultRetention time.Duration
}

func (o *Options) withDefaults() {
	if o.TTL <= 0 {
		o.TTL = 15 * time.Minute
	}
	if o.Lease <= 0 {
		o.Lease = 2 * time.Minute
	}
	if o.ResultRetention <= 0 {
		o.ResultRetention = 30 * 24 * time.Hour
	}
}

type Store struct {
	client *goredis.Client
	ttl    time.Duration
	lease  time.Duration
	retain time.Duration
}

func New(client *goredis.Client, options Options) *Store {
	options.withDefaults()
	return &Store{client: client, ttl: options.TTL, lease: options.Lease, retain: options.ResultRetention}
}

func Key(uploadID string) string { return "skill:upload:" + uploadID }

func (s *Store) Create(ctx context.Context, session Session) error {
	if s == nil || s.client == nil {
		return errors.New("redis upload session store is unavailable")
	}
	if strings.TrimSpace(session.UploadID) == "" || strings.TrimSpace(session.ObjectKey) == "" || strings.TrimSpace(session.Name) == "" {
		return errors.New("invalid skill upload session")
	}
	session.State = statePending
	values := map[string]interface{}{
		"upload_id":          session.UploadID,
		"state":              session.State,
		"owner_id":           session.OwnerID,
		"object_key":         session.ObjectKey,
		"name":               session.Name,
		"description":        session.Description,
		"sha256":             session.SHA256,
		"file_count":         session.FileCount,
		"total_size":         session.TotalSize,
		"package_size":       session.PackageSize,
		"confirmed_skill_id": 0,
	}
	key := Key(session.UploadID)
	// HSET and EXPIRE must be committed together.  A process or network
	// failure between two independent commands could otherwise leave an
	// immortal upload session in Redis.
	_, err := s.client.TxPipelined(ctx, func(pipe goredis.Pipeliner) error {
		pipe.HSet(ctx, key, values)
		pipe.Expire(ctx, key, redisTTL(s.ttl))
		return nil
	})
	return err
}

func (s *Store) Get(ctx context.Context, uploadID string) (*Session, error) {
	if s == nil || s.client == nil {
		return nil, errors.New("redis upload session store is unavailable")
	}
	values, err := s.client.HGetAll(ctx, Key(uploadID)).Result()
	if err != nil {
		return nil, err
	}
	if len(values) == 0 {
		return nil, ErrNotFound
	}
	return decode(values)
}

type BeginResult struct {
	Session  *Session
	Token    string
	Lease    time.Time
	Acquired bool
}

// BeginConfirm atomically claims a pending session or reports an active lease.
// A new token is generated by the caller and is required for every subsequent
// state mutation, fencing stale requests after a lease takeover.
func (s *Store) BeginConfirm(ctx context.Context, uploadID, ownerID, token string, now time.Time) (*BeginResult, error) {
	if s == nil || s.client == nil {
		return nil, errors.New("redis upload session store is unavailable")
	}
	if token == "" {
		return nil, errors.New("confirmation token is required")
	}
	script := redisScript(`
local state = redis.call('HGET', KEYS[1], 'state')
if not state then return {'missing'} end
local stored_owner = redis.call('HGET', KEYS[1], 'owner_id') or ''
if stored_owner ~= ARGV[1] then return {'owner'} end
if state == 'confirmed' then return {'confirmed'} end
if state == 'failed' then return {'failed'} end
local until_value = tonumber(redis.call('HGET', KEYS[1], 'confirm_lease_until') or '0')
local now_value = tonumber(ARGV[2])
if state == 'confirming' and until_value > now_value then
  return {'processing', tostring(until_value)}
end
local lease_until = now_value + tonumber(ARGV[4])
redis.call('HSET', KEYS[1], 'state', 'confirming', 'confirm_token', ARGV[3], 'confirm_lease_until', tostring(lease_until))
redis.call('EXPIRE', KEYS[1], ARGV[5])
return {'acquired', tostring(lease_until)}
`)
	result, err := s.client.Eval(ctx, string(script), []string{Key(uploadID)}, ownerID, strconv.FormatInt(now.Unix(), 10), token, strconv.FormatInt(int64(redisTTL(s.lease).Seconds()), 10), strconv.FormatInt(int64(redisTTL(s.ttl+s.lease).Seconds()), 10)).Result()
	if err != nil {
		return nil, err
	}
	parts, ok := result.([]interface{})
	if !ok || len(parts) == 0 {
		return nil, errors.New("invalid redis confirmation result")
	}
	status := fmt.Sprint(parts[0])
	session, getErr := s.Get(ctx, uploadID)
	if getErr != nil {
		return nil, getErr
	}
	switch status {
	case "acquired":
		leaseUnix, _ := strconv.ParseInt(fmt.Sprint(parts[1]), 10, 64)
		return &BeginResult{Session: session, Token: token, Lease: time.Unix(leaseUnix, 0), Acquired: true}, nil
	case "processing":
		leaseUnix, _ := strconv.ParseInt(fmt.Sprint(parts[1]), 10, 64)
		session.ConfirmLeaseUntil = time.Unix(leaseUnix, 0)
		return &BeginResult{Session: session, Lease: session.ConfirmLeaseUntil}, ErrConfirmRunning
	case "confirmed":
		return &BeginResult{Session: session}, nil
	case "failed":
		return &BeginResult{Session: session}, ErrConfirmFailed
	case "owner":
		return nil, ErrOwnerMismatch
	default:
		return nil, ErrNotFound
	}
}

func (s *Store) MarkConfirmed(ctx context.Context, uploadID, token string, skillID uint, sha string) error {
	return s.markState(ctx, uploadID, token, stateConfirmed, map[string]interface{}{
		"confirmed_skill_id": skillID,
		"sha256":             sha,
	}, s.retain)
}

func (s *Store) MarkPending(ctx context.Context, uploadID, token string) error {
	return s.markState(ctx, uploadID, token, statePending, map[string]interface{}{}, s.ttl)
}

func (s *Store) MarkFailed(ctx context.Context, uploadID, token, message string) error {
	return s.markState(ctx, uploadID, token, stateFailed, map[string]interface{}{"last_error": message}, s.retain)
}

func (s *Store) markState(ctx context.Context, uploadID, token, state string, values map[string]interface{}, retention time.Duration) error {
	if s == nil || s.client == nil {
		return errors.New("redis upload session store is unavailable")
	}
	args := []interface{}{token, state, strconv.FormatInt(int64(redisTTL(retention).Seconds()), 10)}
	for key, value := range values {
		args = append(args, key, value)
	}
	script := redisScript(`
local current_state = redis.call('HGET', KEYS[1], 'state')
local current_token = redis.call('HGET', KEYS[1], 'confirm_token')
if current_state ~= 'confirming' or current_token ~= ARGV[1] then return 0 end
redis.call('HSET', KEYS[1], 'state', ARGV[2])
redis.call('HDEL', KEYS[1], 'confirm_token', 'confirm_lease_until')
local i = 4
while i <= #ARGV do redis.call('HSET', KEYS[1], ARGV[i], ARGV[i + 1]); i = i + 2 end
redis.call('EXPIRE', KEYS[1], ARGV[3])
return 1
`)
	result, err := s.client.Eval(ctx, string(script), []string{Key(uploadID)}, args...).Int()
	if err != nil {
		return err
	}
	if result != 1 {
		return ErrLeaseLost
	}
	return nil
}

func redisTTL(value time.Duration) time.Duration {
	if value < time.Second {
		return time.Second
	}
	return value
}

func decode(values map[string]string) (*Session, error) {
	intValue := func(key string) (int64, error) {
		if values[key] == "" {
			return 0, nil
		}
		return strconv.ParseInt(values[key], 10, 64)
	}
	fileCount, err := intValue("file_count")
	if err != nil {
		return nil, err
	}
	totalSize, err := intValue("total_size")
	if err != nil {
		return nil, err
	}
	packageSize, err := intValue("package_size")
	if err != nil {
		return nil, err
	}
	skillID, err := intValue("confirmed_skill_id")
	if err != nil {
		return nil, err
	}
	leaseUnix, err := intValue("confirm_lease_until")
	if err != nil {
		return nil, err
	}
	return &Session{
		UploadID: values["upload_id"], State: values["state"], OwnerID: values["owner_id"],
		ObjectKey: values["object_key"], Name: values["name"], Description: values["description"],
		SHA256: values["sha256"], FileCount: int(fileCount), TotalSize: totalSize, PackageSize: packageSize,
		ConfirmedSkillID: uint(skillID), ConfirmLeaseUntil: time.Unix(leaseUnix, 0), ConfirmToken: values["confirm_token"],
	}, nil
}

type redisScript string

func (s redisScript) String() string { return string(s) }

// Keep JSON encoding available for callers that want to log/audit a redacted
// session without ever serializing the fencing token.
func (s *Session) MarshalJSON() ([]byte, error) {
	type alias Session
	return json.Marshal((*alias)(s))
}
