package service

import (
	"archive/zip"
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"syscall"
	"time"
	"unicode/utf8"

	"gopkg.in/yaml.v3"
)

const (
	MaxUploadSize       int64 = 10 * 1024 * 1024
	MaxPackageSize      int64 = 12 * 1024 * 1024
	MaxFileSize         int64 = 10 * 1024 * 1024
	MaxUnpackedSize     int64 = 50 * 1024 * 1024
	MaxCompressionRatio       = 100
	MaxFileCount        int   = 200
	// MaxUnzipSize is kept as a compatibility alias for callers that used the
	// old single-limit API; new code must distinguish upload/package/unpacked
	// limits above.
	MaxUnzipSize          int64 = MaxPackageSize
	SkillMDFile                 = "SKILL.md"
	MinSkillTempFreeBytes int64 = 1 << 30
)

const MaxSkillNameLength = 128

var skillUploadIDPattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9_-]{7,63}$`)

// ValidateSkillUploadID accepts the current UUID IDs and future opaque IDs
// such as ULIDs while rejecting values that could alter Redis keys or object
// paths.  IDs are generated by the Backend; this check is only a boundary
// guard for client-supplied confirmation requests.
func ValidateSkillUploadID(id string) error {
	if !skillUploadIDPattern.MatchString(id) {
		return ErrBadRequest("invalid upload_id")
	}
	return nil
}

// NormalizeSkillName is the shared object-key and API name policy.  Keeping it
// in the validator package makes upload, legacy migration, and object-key
// construction reject the same path/control-character edge cases.
func NormalizeSkillName(name string) (string, error) {
	name = strings.TrimSpace(name)
	if name == "" || name == "." || name == ".." {
		return "", ErrBadRequest("skill name is required")
	}
	if len([]rune(name)) > MaxSkillNameLength {
		return "", ErrBadRequest("skill name is too long")
	}
	if strings.ContainsAny(name, "/\\") {
		return "", ErrBadRequest("skill name is invalid")
	}
	for _, r := range name {
		if r < 0x20 || r == 0x7f {
			return "", ErrBadRequest("skill name is invalid")
		}
	}
	return name, nil
}

func CheckSkillTempFreeSpace(root string, minimum int64) error {
	if root == "" {
		root = os.TempDir()
	}
	if minimum <= 0 {
		minimum = MinSkillTempFreeBytes
	}
	var stat syscall.Statfs_t
	if err := syscall.Statfs(root, &stat); err != nil {
		return fmt.Errorf("stat Skill temp volume: %w", err)
	}
	free := int64(stat.Bavail) * int64(stat.Bsize)
	if free < minimum {
		return fmt.Errorf("Skill temp volume free space %d bytes is below reserved %d bytes", free, minimum)
	}
	return nil
}

// EnsureSkillTempRoot creates and validates the private staging root used by
// the upload path.  A symlink at any path component is rejected so an
// operator cannot accidentally redirect extraction into an unrelated tree.
func EnsureSkillTempRoot(root string) error {
	if strings.TrimSpace(root) == "" {
		return fmt.Errorf("Skill temp root is required")
	}
	abs, err := filepath.Abs(root)
	if err != nil {
		return fmt.Errorf("resolve Skill temp root: %w", err)
	}
	// MkdirAll follows a symlink in a parent component. Walk existing
	// components first so a rejected configuration cannot create staging data
	// in an unrelated target before validation notices the link.
	if err := ensurePrivateDirPath(abs); err != nil {
		return fmt.Errorf("create Skill temp root: %w", err)
	}
	info, err := os.Lstat(abs)
	if err != nil {
		return fmt.Errorf("inspect Skill temp root: %w", err)
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.IsDir() {
		return fmt.Errorf("Skill temp root must be a real directory")
	}
	resolved, err := filepath.EvalSymlinks(abs)
	if err != nil {
		return fmt.Errorf("resolve Skill temp root links: %w", err)
	}
	if filepath.Clean(resolved) != filepath.Clean(abs) {
		return fmt.Errorf("Skill temp root must not contain symlinks")
	}
	if err := os.Chmod(abs, 0o700); err != nil {
		return fmt.Errorf("secure Skill temp root: %w", err)
	}
	return nil
}

func ensurePrivateDirPath(abs string) error {
	volume := filepath.VolumeName(abs)
	remainder := strings.TrimPrefix(abs, volume)
	current := volume
	if strings.HasPrefix(remainder, string(filepath.Separator)) {
		current += string(filepath.Separator)
		remainder = strings.TrimPrefix(remainder, string(filepath.Separator))
	}
	if current == "" {
		current = "."
	}
	for _, component := range strings.Split(remainder, string(filepath.Separator)) {
		if component == "" || component == "." {
			continue
		}
		current = filepath.Join(current, component)
		info, err := os.Lstat(current)
		if errors.Is(err, os.ErrNotExist) {
			if err := os.Mkdir(current, 0o700); err != nil && !errors.Is(err, os.ErrExist) {
				return err
			}
			info, err = os.Lstat(current)
		}
		if err != nil {
			return err
		}
		if info.Mode()&os.ModeSymlink != 0 || !info.IsDir() {
			return fmt.Errorf("path component %q is not a real directory", current)
		}
	}
	return nil
}

// ZipLimits is the single source of truth for archive resource limits.  The
// exported constants preserve the historical defaults for callers that do not
// have a config object yet.
type ZipLimits struct {
	UploadSize       int64
	PackageSize      int64
	FileSize         int64
	UnpackedSize     int64
	CompressionRatio int64
	FileCount        int
}

func DefaultZipLimits() ZipLimits {
	return ZipLimits{
		UploadSize: MaxUploadSize, PackageSize: MaxPackageSize, FileSize: MaxFileSize,
		UnpackedSize: MaxUnpackedSize, CompressionRatio: MaxCompressionRatio, FileCount: MaxFileCount,
	}
}

func (l ZipLimits) withDefaults() ZipLimits {
	d := DefaultZipLimits()
	if l.UploadSize <= 0 {
		l.UploadSize = d.UploadSize
	}
	if l.PackageSize <= 0 {
		l.PackageSize = d.PackageSize
	}
	if l.FileSize <= 0 {
		l.FileSize = d.FileSize
	}
	if l.UnpackedSize <= 0 {
		l.UnpackedSize = d.UnpackedSize
	}
	if l.CompressionRatio <= 0 {
		l.CompressionRatio = d.CompressionRatio
	}
	if l.FileCount <= 0 {
		l.FileCount = d.FileCount
	}
	return l
}

func NormalizeZipLimits(l ZipLimits) ZipLimits { return l.withDefaults() }

type ValidationResult struct {
	Valid              bool     `json:"valid"`
	Name               string   `json:"name,omitempty"`
	Description        string   `json:"description,omitempty"`
	FileCount          int      `json:"file_count,omitempty"`
	Files              []string `json:"files,omitempty"`
	ContainsExecutable bool     `json:"contains_executable,omitempty"`
	ContainsBinary     bool     `json:"contains_binary,omitempty"`
	TotalSize          int64    `json:"total_size,omitempty"`
	TmpDir             string   `json:"tmp_dir,omitempty"`
	UploadID           string   `json:"upload_id,omitempty"`
	UploadedBy         string   `json:"uploaded_by,omitempty"`
	ObjectKey          string   `json:"-"`
	SHA256             string   `json:"sha256,omitempty"`
	PackageSize        int64    `json:"package_size,omitempty"`
	StorageType        string   `json:"storage_type,omitempty"`
	Errors             []string `json:"errors,omitempty"`
}

type frontmatterData struct {
	Name        string `yaml:"name"`
	Description string `yaml:"description"`
}

// ValidateZip 解压到临时目录并校验
func ValidateZip(zipData []byte) (*ValidationResult, string, error) {
	return ValidateZipReaderAt(bytes.NewReader(zipData), int64(len(zipData)))
}

// ValidateZipReaderAt validates an on-disk/random-access ZIP without first
// materializing the complete upload in memory.  The caller owns the reader and
// must provide its exact size.
func ValidateZipReaderAt(source io.ReaderAt, size int64) (*ValidationResult, string, error) {
	return ValidateZipReaderAtContext(context.Background(), source, size, "")
}

func ValidateZipReaderAtInDir(source io.ReaderAt, size int64, tempRoot string) (*ValidationResult, string, error) {
	return ValidateZipReaderAtContext(context.Background(), source, size, tempRoot)
}

func ValidateZipReaderAtContext(ctx context.Context, source io.ReaderAt, size int64, tempRoot string) (*ValidationResult, string, error) {
	return ValidateZipReaderAtContextWithLimits(ctx, source, size, tempRoot, DefaultZipLimits())
}

func ValidateZipReaderAtContextWithLimits(ctx context.Context, source io.ReaderAt, size int64, tempRoot string, limits ZipLimits) (*ValidationResult, string, error) {
	limits = limits.withDefaults()
	reader, err := zip.NewReader(source, size)
	if err != nil {
		return &ValidationResult{Valid: false, Errors: []string{"invalid zip file"}}, "", err
	}

	// 创建临时目录
	tmpDir, err := os.MkdirTemp(tempRoot, "skill-upload-*")
	if err != nil {
		return nil, "", fmt.Errorf("create temp dir: %w", err)
	}

	var (
		totalSize          int64
		fileCount          int
		errors             []string
		hasSkillMD         bool
		fmName             string
		fmDesc             string
		seenNames          = make(map[string]struct{}, len(reader.File))
		fileNames          []string
		containsExecutable bool
		containsBinary     bool
	)

	for _, f := range reader.File {
		if err := ctx.Err(); err != nil {
			_ = os.RemoveAll(tmpDir)
			return nil, tmpDir, err
		}
		cleanName, err := normalizeZipEntryName(f.Name)
		if err != nil {
			errors = append(errors, err.Error())
			continue
		}
		if f.NonUTF8 || !utf8.ValidString(f.Name) {
			errors = append(errors, "zip entry name must be UTF-8")
			continue
		}
		// Treat an explicit directory suffix as the same logical path as its
		// file spelling.  Otherwise an archive containing both ``foo`` and
		// ``foo/`` could evade duplicate detection and rely on filesystem
		// extraction order to decide which entry wins.
		collisionName := strings.ToLower(strings.TrimSuffix(cleanName, "/"))
		if _, exists := seenNames[collisionName]; exists {
			errors = append(errors, fmt.Sprintf("duplicate zip entry: %s", cleanName))
			continue
		}
		seenNames[collisionName] = struct{}{}

		// 链接、设备、管道和 socket 都不属于 Skill 普通文件。
		if f.Mode()&(os.ModeSymlink|os.ModeDevice|os.ModeNamedPipe|os.ModeSocket) != 0 {
			errors = append(errors, "special file types are not allowed")
			continue
		}

		destPath := filepath.Join(tmpDir, filepath.FromSlash(cleanName))
		if !isPathInside(tmpDir, destPath) {
			errors = append(errors, "path traversal detected")
			continue
		}

		if f.FileInfo().IsDir() {
			if err := os.MkdirAll(destPath, 0o755); err != nil {
				errors = append(errors, fmt.Sprintf("cannot create directory %s: %v", cleanName, err))
			}
			continue
		}
		if f.UncompressedSize64 > uint64(limits.FileSize) {
			errors = append(errors, fmt.Sprintf("file exceeds %dMB limit", limits.FileSize/1024/1024))
			continue
		}
		if compressionRatioExceeded(f.UncompressedSize64, f.CompressedSize64, limits.CompressionRatio) {
			errors = append(errors, fmt.Sprintf("compression ratio exceeds %d:1", limits.CompressionRatio))
			continue
		}
		if f.UncompressedSize64 > uint64(limits.UnpackedSize-totalSize) {
			errors = append(errors, fmt.Sprintf("zip bomb: total size exceeds %dMB", limits.UnpackedSize/1024/1024))
			_ = os.RemoveAll(tmpDir)
			return &ValidationResult{Valid: false, Errors: errors}, tmpDir, nil
		}

		// 确保父目录存在
		if err := os.MkdirAll(filepath.Dir(destPath), 0o755); err != nil {
			errors = append(errors, fmt.Sprintf("cannot create directory for %s: %v", cleanName, err))
			continue
		}

		rc, err := f.Open()
		if err != nil {
			errors = append(errors, fmt.Sprintf("cannot open %s: %v", cleanName, err))
			continue
		}

		remaining := limits.UnpackedSize - totalSize
		perFileRemaining := limits.FileSize
		if remaining < perFileRemaining {
			perFileRemaining = remaining
		}
		destMode := os.FileMode(0o644)
		if f.Mode().Perm()&0o111 != 0 {
			destMode = 0o755
		}
		destFile, err := os.OpenFile(destPath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, destMode)
		if err != nil {
			rc.Close()
			errors = append(errors, fmt.Sprintf("cannot create %s: %v", cleanName, err))
			continue
		}
		if err := destFile.Chmod(destMode); err != nil {
			_ = destFile.Close()
			rc.Close()
			errors = append(errors, fmt.Sprintf("cannot secure %s: %v", cleanName, err))
			continue
		}
		n, err := io.Copy(destFile, io.LimitReader(contextReader{ctx: ctx, reader: rc}, perFileRemaining+1))
		closeErr := destFile.Close()
		rc.Close()
		if err != nil {
			errors = append(errors, fmt.Sprintf("cannot read %s: %v", cleanName, err))
			continue
		}
		if closeErr != nil {
			errors = append(errors, fmt.Sprintf("cannot write %s: %v", cleanName, closeErr))
			continue
		}
		if n > perFileRemaining {
			errors = append(errors, fmt.Sprintf("file exceeds %dMB limit", limits.FileSize/1024/1024))
			_ = os.RemoveAll(tmpDir)
			return &ValidationResult{Valid: false, Errors: errors}, tmpDir, nil
		}

		totalSize += n
		fileCount++
		fileNames = append(fileNames, cleanName)
		if f.Mode().Perm()&0o111 != 0 {
			containsExecutable = true
		}
		binary, binaryErr := fileLooksBinary(destPath)
		if binaryErr != nil {
			errors = append(errors, fmt.Sprintf("cannot inspect binary content for %s: %v", cleanName, binaryErr))
			continue
		}
		if binary {
			containsBinary = true
		}

		// Zip bomb 检查
		if fileCount > limits.FileCount {
			errors = append(errors, fmt.Sprintf("too many files: exceeds %d", limits.FileCount))
			os.RemoveAll(tmpDir)
			return &ValidationResult{Valid: false, Errors: errors}, tmpDir, nil
		}

		// 检查 SKILL.md（根目录或一级子目录，如 skill-name/SKILL.md）
		if filepath.Base(cleanName) == SkillMDFile && !strings.Contains(filepath.Dir(cleanName), "/") {
			hasSkillMD = true
			data, readErr := os.ReadFile(destPath)
			if readErr != nil {
				errors = append(errors, fmt.Sprintf("cannot read %s: %v", cleanName, readErr))
				continue
			}
			name, desc, parseErr := parseFrontmatter(data)
			if parseErr != nil {
				errors = append(errors, parseErr.Error())
			} else {
				fmName = name
				fmDesc = desc
			}
		}
	}

	if !hasSkillMD {
		errors = append(errors, "missing SKILL.md")
	}
	if entries, readErr := os.ReadDir(tmpDir); readErr == nil {
		rootDirs := make([]string, 0, 1)
		rootFiles := 0
		_, rootSkillErr := os.Stat(filepath.Join(tmpDir, SkillMDFile))
		hasRootSkillMD := rootSkillErr == nil
		for _, entry := range entries {
			if entry.IsDir() {
				rootDirs = append(rootDirs, entry.Name())
			} else {
				rootFiles++
			}
		}
		// A root-level SKILL.md makes the package root the Skill root, so content
		// files and directories may sit beside it.  The alternate layout is
		// exactly one named top-level Skill directory with no sibling files.
		rootLayout := hasRootSkillMD
		nestedLayout := !hasRootSkillMD && len(rootDirs) == 1 && rootFiles == 0 && fmName != "" && rootDirs[0] == fmName
		if !rootLayout && !nestedLayout {
			errors = append(errors, "zip must contain a root SKILL.md or one top-level Skill directory matching SKILL.md.name")
		}
	} else {
		errors = append(errors, fmt.Sprintf("cannot inspect Skill root: %v", readErr))
	}

	if len(errors) > 0 {
		return &ValidationResult{Valid: false, Errors: errors}, tmpDir, nil
	}

	sort.Strings(fileNames)
	return &ValidationResult{
		Valid:              true,
		Name:               fmName,
		Description:        fmDesc,
		FileCount:          fileCount,
		Files:              fileNames,
		ContainsExecutable: containsExecutable,
		ContainsBinary:     containsBinary,
		TotalSize:          totalSize,
		TmpDir:             tmpDir,
	}, tmpDir, nil
}

// ValidateCanonicalSkillPackageContext rechecks a generated, deterministic
// ZIP with the same limits used for the source archive.  Repacking can change
// the compression ratio (for example, a stored input may become highly
// compressed), so validating only the original upload is not sufficient for
// the AgentEnd boundary.
func ValidateCanonicalSkillPackageContext(ctx context.Context, source io.ReaderAt, size int64, tempRoot, expectedName string, limits ZipLimits) error {
	result, tmpDir, err := ValidateZipReaderAtContextWithLimits(ctx, source, size, tempRoot, limits)
	if tmpDir != "" {
		defer os.RemoveAll(tmpDir)
	}
	if err != nil {
		return fmt.Errorf("canonical Skill package validation failed: %w", err)
	}
	if err := ctx.Err(); err != nil {
		return err
	}
	if result == nil || !result.Valid {
		if result != nil && len(result.Errors) > 0 {
			return fmt.Errorf("canonical Skill package validation failed: %s", strings.Join(result.Errors, "; "))
		}
		return fmt.Errorf("canonical Skill package validation failed")
	}
	if expectedName != "" && result.Name != expectedName {
		return fmt.Errorf("canonical Skill package name %q does not match %q", result.Name, expectedName)
	}
	return nil
}

func compressionRatioExceeded(uncompressed, compressed uint64, ratio int64) bool {
	if uncompressed == 0 {
		return false
	}
	if compressed == 0 || ratio <= 0 {
		return true
	}
	// Compare ceil(uncompressed/ratio) with compressed to avoid multiplying
	// attacker-controlled ZIP64 fields and overflowing uint64.
	divisor := uint64(ratio)
	minimumCompressed := uncompressed / divisor
	if uncompressed%divisor != 0 {
		minimumCompressed++
	}
	return minimumCompressed > compressed
}

type contextReader struct {
	ctx    context.Context
	reader io.Reader
}

func fileLooksBinary(path string) (bool, error) {
	file, err := os.Open(path)
	if err != nil {
		return false, err
	}
	defer file.Close()
	buf := make([]byte, 8192)
	n, err := file.Read(buf)
	if err != nil && err != io.EOF {
		return false, err
	}
	return bytes.IndexByte(buf[:n], 0) >= 0, nil
}

func (r contextReader) Read(p []byte) (int, error) {
	select {
	case <-r.ctx.Done():
		return 0, r.ctx.Err()
	default:
		return r.reader.Read(p)
	}
}

func normalizeZipEntryName(name string) (string, error) {
	if name == "" {
		return "", fmt.Errorf("empty zip entry name")
	}
	if name != strings.TrimSpace(name) {
		return "", fmt.Errorf("non-canonical zip entry path")
	}
	for _, r := range name {
		if r < 0x20 || r == 0x7f {
			return "", fmt.Errorf("control characters are not allowed in zip entry names")
		}
	}
	if strings.Contains(name, "\\") {
		return "", fmt.Errorf("backslash path separator not allowed")
	}
	if filepath.IsAbs(name) || strings.HasPrefix(name, "/") {
		return "", fmt.Errorf("absolute path not allowed")
	}
	// Reject non-canonical spellings before filepath.Clean can hide a
	// traversal segment.  A path such as foo/../SKILL.md stays inside the
	// extraction root, but accepting it would make Backend and AgentEnd
	// disagree about duplicate/canonical entries and could bypass manifest
	// comparisons.  Directory entries may have one trailing slash only.
	trailingSlash := strings.HasSuffix(name, "/")
	trimmedName := strings.TrimSuffix(name, "/")
	parts := strings.Split(trimmedName, "/")
	if trimmedName == "" || len(parts) == 0 {
		return "", fmt.Errorf("empty zip entry name")
	}
	for _, segment := range parts {
		if segment == "" || segment == "." || segment == ".." {
			return "", fmt.Errorf("non-canonical zip entry path")
		}
	}
	canonical := strings.Join(parts, "/")
	if trailingSlash {
		// Keep the normalized entry name free of a trailing slash; the archive
		// metadata still determines whether it is a directory.
		name = canonical + "/"
	} else {
		name = canonical
	}
	cleanName := filepath.ToSlash(filepath.Clean(name))
	if cleanName == "." || cleanName == "" {
		return "", fmt.Errorf("empty zip entry name")
	}
	if strings.Contains(strings.Split(cleanName, "/")[0], ":") {
		return "", fmt.Errorf("drive-qualified zip entry path not allowed")
	}
	return cleanName, nil
}

func isPathInside(baseDir, targetPath string) bool {
	rel, err := filepath.Rel(baseDir, targetPath)
	if err != nil {
		return false
	}
	return rel != "." && rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator))
}

// parseFrontmatter 解析 SKILL.md 的 YAML frontmatter
func parseFrontmatter(data []byte) (name, description string, err error) {
	if !utf8.Valid(data) {
		return "", "", fmt.Errorf("SKILL.md must be UTF-8")
	}
	content := strings.ReplaceAll(string(data), "\r\n", "\n")
	if !strings.HasPrefix(content, "---\n") {
		return "", "", fmt.Errorf("missing frontmatter")
	}
	lines := strings.Split(content[4:], "\n")
	closing := -1
	for index, line := range lines {
		if strings.TrimSpace(line) == "---" {
			closing = index
			break
		}
	}
	if closing < 0 {
		return "", "", fmt.Errorf("missing frontmatter")
	}
	fmContent := strings.TrimSpace(strings.Join(lines[:closing], "\n"))
	var fm frontmatterData
	if err := yaml.Unmarshal([]byte(fmContent), &fm); err != nil {
		return "", "", fmt.Errorf("invalid frontmatter: %v", err)
	}

	name, nameErr := NormalizeSkillName(fm.Name)
	if nameErr != nil {
		return "", "", nameErr
	}
	if len([]rune(fm.Description)) > 4096 {
		return "", "", fmt.Errorf("description field is too long")
	}

	return name, fm.Description, nil
}

// PackValidatedSkillDir 将已校验的技能目录重新打包为 zip 字节流。
func PackValidatedSkillDir(name string, tmpDir string) ([]byte, error) {
	return PackValidatedSkillDirWithLimit(name, tmpDir, MaxPackageSize)
}

// PackValidatedSkillDirWithLimit is the compatibility-path counterpart of
// the streaming packer. It keeps the legacy API bounded when an operator uses
// a stricter configured package limit.
func PackValidatedSkillDirWithLimit(name string, tmpDir string, maxPackageSize int64) ([]byte, error) {
	srcDir, err := validatedSkillSourceDir(name, tmpDir)
	if err != nil {
		return nil, err
	}

	// 将已校验的文件重新打包为 zip
	zipData, err := zipDirWithLimit(srcDir, maxPackageSize)
	if err != nil {
		return nil, fmt.Errorf("pack skill files: %w", err)
	}

	return zipData, nil
}

// PackValidatedSkillDirInRoot is the trusted counterpart used immediately
// after ValidateZipReaderAtContext.  The validator may be configured with a
// private volume outside os.TempDir; the legacy public helper deliberately
// keeps its stricter system-temp check because it accepts client-supplied
// paths during the compatibility confirm flow.
func PackValidatedSkillDirInRoot(name, tmpDir, tempRoot string) ([]byte, error) {
	return PackValidatedSkillDirInRootContext(context.Background(), name, tmpDir, tempRoot)
}

// PackValidatedSkillDirInRootContext is the cancellation-aware variant used
// by uploads and migration. Packing reads every extracted file, so checking
// only the unzip phase would allow slow filesystem I/O to outlive the request
// validation deadline.
func PackValidatedSkillDirInRootContext(ctx context.Context, name, tmpDir, tempRoot string) ([]byte, error) {
	return PackValidatedSkillDirInRootContextWithLimit(ctx, name, tmpDir, tempRoot, MaxPackageSize)
}

// PackValidatedSkillDirInRootContextWithLimit aborts as soon as the
// deterministic archive exceeds maxPackageSize instead of constructing an
// oversized ZIP and checking it only after the write has completed.
func PackValidatedSkillDirInRootContextWithLimit(ctx context.Context, name, tmpDir, tempRoot string, maxPackageSize int64) ([]byte, error) {
	srcDir, err := validatedSkillSourceDirInRoot(name, tmpDir, tempRoot)
	if err != nil {
		return nil, err
	}
	if maxPackageSize <= 0 {
		maxPackageSize = MaxPackageSize
	}
	var buf bytes.Buffer
	err = zipDirToWriterContext(ctx, srcDir, &limitedWriter{dst: &buf, limit: maxPackageSize})
	if err != nil {
		return nil, fmt.Errorf("pack skill files: %w", err)
	}
	return buf.Bytes(), nil
}

// PackValidatedSkillDirToFile writes the canonical package directly to a
// 0600 temporary file while hashing the bytes.  It is used by the MinIO upload
// path so the complete canonical ZIP never has to exist as a []byte.
func PackValidatedSkillDirToFile(name, tmpDir, destination string) (size int64, sha string, err error) {
	return PackValidatedSkillDirToFileContext(context.Background(), name, tmpDir, destination)
}

func PackValidatedSkillDirToFileContext(ctx context.Context, name, tmpDir, destination string) (size int64, sha string, err error) {
	srcDir, err := validatedSkillSourceDir(name, tmpDir)
	if err != nil {
		return 0, "", err
	}
	return packValidatedSkillDirToFileContext(ctx, srcDir, destination, MaxPackageSize)
}

// PackValidatedSkillDirToFileInRoot is the streaming variant for a validator
// configured with a dedicated temp volume.
func PackValidatedSkillDirToFileInRoot(name, tmpDir, destination, tempRoot string) (size int64, sha string, err error) {
	return PackValidatedSkillDirToFileInRootContext(context.Background(), name, tmpDir, destination, tempRoot)
}

func PackValidatedSkillDirToFileInRootContext(ctx context.Context, name, tmpDir, destination, tempRoot string) (size int64, sha string, err error) {
	return PackValidatedSkillDirToFileInRootContextWithLimit(ctx, name, tmpDir, destination, tempRoot, MaxPackageSize)
}

// PackValidatedSkillDirToFileInRootContextWithLimit is the streaming
// canonical-pack path used by MinIO uploads and migrations.
func PackValidatedSkillDirToFileInRootContextWithLimit(ctx context.Context, name, tmpDir, destination, tempRoot string, maxPackageSize int64) (size int64, sha string, err error) {
	srcDir, err := validatedSkillSourceDirInRoot(name, tmpDir, tempRoot)
	if err != nil {
		return 0, "", err
	}
	return packValidatedSkillDirToFileContext(ctx, srcDir, destination, maxPackageSize)
}

func packValidatedSkillDirToFile(srcDir, destination string) (size int64, sha string, err error) {
	return packValidatedSkillDirToFileContext(context.Background(), srcDir, destination, MaxPackageSize)
}

func packValidatedSkillDirToFileContext(ctx context.Context, srcDir, destination string, maxPackageSize int64) (size int64, sha string, err error) {
	file, err := os.OpenFile(destination, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o600)
	if err != nil {
		return 0, "", fmt.Errorf("create canonical package: %w", err)
	}
	hasher := sha256.New()
	if maxPackageSize <= 0 {
		maxPackageSize = MaxPackageSize
	}
	if err := zipDirToWriterContext(ctx, srcDir, &limitedWriter{dst: io.MultiWriter(file, hasher), limit: maxPackageSize}); err != nil {
		_ = file.Close()
		_ = os.Remove(destination)
		return 0, "", fmt.Errorf("pack skill files: %w", err)
	}
	if err := file.Sync(); err != nil {
		_ = file.Close()
		_ = os.Remove(destination)
		return 0, "", fmt.Errorf("sync canonical package: %w", err)
	}
	if err := file.Close(); err != nil {
		_ = os.Remove(destination)
		return 0, "", fmt.Errorf("close canonical package: %w", err)
	}
	info, err := os.Stat(destination)
	if err != nil {
		_ = os.Remove(destination)
		return 0, "", err
	}
	return info.Size(), hex.EncodeToString(hasher.Sum(nil)), nil
}

func InspectValidatedSkillDir(name string, tmpDir string) (*ValidationResult, error) {
	return InspectValidatedSkillDirWithLimits(name, tmpDir, DefaultZipLimits())
}

// InspectValidatedSkillDirWithLimits re-checks a legacy confirmation directory
// using the same resource limits as the upload validator.  The legacy wrapper
// above remains for callers that intentionally use the default policy.
func InspectValidatedSkillDirWithLimits(name string, tmpDir string, limits ZipLimits) (*ValidationResult, error) {
	srcDir, err := validatedSkillSourceDir(name, tmpDir)
	if err != nil {
		return nil, err
	}
	return inspectValidatedSkillSourceDir(name, srcDir, limits)
}

// InspectValidatedSkillDirInRoot is the configured-temp-root variant used by
// the rolling-upgrade confirmation bridge.  It does not fall back to the
// process-wide temporary directory.
func InspectValidatedSkillDirInRoot(name, tmpDir, tempRoot string, limits ZipLimits) (*ValidationResult, error) {
	srcDir, err := validatedSkillSourceDirInRoot(name, tmpDir, tempRoot)
	if err != nil {
		return nil, err
	}
	return inspectValidatedSkillSourceDir(name, srcDir, limits)
}

func inspectValidatedSkillSourceDir(name, srcDir string, limits ZipLimits) (*ValidationResult, error) {
	limits = limits.withDefaults()

	result := &ValidationResult{Valid: true}
	err := filepath.Walk(srcDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return fmt.Errorf("walk error at %s: %w", path, err)
		}
		if info.Mode()&(os.ModeSymlink|os.ModeDevice|os.ModeNamedPipe|os.ModeSocket) != 0 {
			return fmt.Errorf("symbolic links and special file types are not allowed")
		}
		if info.IsDir() {
			return nil
		}

		result.FileCount++
		if result.FileCount > limits.FileCount {
			return fmt.Errorf("too many files: exceeds %d", limits.FileCount)
		}
		result.TotalSize += info.Size()
		if info.Size() > limits.FileSize {
			return fmt.Errorf("file exceeds %dMB limit", limits.FileSize/1024/1024)
		}
		if result.TotalSize > limits.UnpackedSize {
			return fmt.Errorf("total size exceeds %dMB", limits.UnpackedSize/1024/1024)
		}

		rel, err := filepath.Rel(srcDir, path)
		if err != nil {
			return fmt.Errorf("relative path error: %w", err)
		}
		rel = filepath.ToSlash(rel)
		result.Files = append(result.Files, rel)
		if info.Mode().Perm()&0o111 != 0 {
			result.ContainsExecutable = true
		}
		binary, binaryErr := fileLooksBinary(path)
		if binaryErr != nil {
			return fmt.Errorf("inspect binary content at %s: %w", rel, binaryErr)
		}
		if binary {
			result.ContainsBinary = true
		}
		if filepath.Base(rel) == SkillMDFile && !strings.Contains(pathpkgDir(rel), "/") {
			data, err := os.ReadFile(path)
			if err != nil {
				return fmt.Errorf("read %s: %w", SkillMDFile, err)
			}
			skillName, desc, err := parseFrontmatter(data)
			if err != nil {
				return err
			}
			result.Name = skillName
			result.Description = desc
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	if result.Name == "" {
		return nil, fmt.Errorf("missing %s", SkillMDFile)
	}
	if result.Name != name {
		return nil, fmt.Errorf("skill name mismatch: confirm name (%s) does not match SKILL.md name (%s)", name, result.Name)
	}
	sort.Strings(result.Files)
	return result, nil
}

func validatedSkillSourceDir(name string, tmpDir string) (string, error) {
	safeTmpDir, err := ensureSkillUploadTmpDir(tmpDir)
	if err != nil {
		return "", err
	}
	return skillSourceDir(name, safeTmpDir), nil
}

func validatedSkillSourceDirInRoot(name, tmpDir, tempRoot string) (string, error) {
	safeTmpDir, err := ensureSkillUploadTmpDirInRoot(tmpDir, tempRoot)
	if err != nil {
		return "", err
	}
	return skillSourceDir(name, safeTmpDir), nil
}

func skillSourceDir(name, safeTmpDir string) string {
	// A root-level SKILL.md defines the package root, even when a sibling
	// directory happens to share the Skill name.  Prefer it before probing the
	// alternate single-top-level-directory layout; otherwise canonical packing
	// could silently omit root-level files from an otherwise valid package.
	if info, err := os.Stat(filepath.Join(safeTmpDir, SkillMDFile)); err == nil && info.Mode().IsRegular() {
		return safeTmpDir
	}
	srcDir := filepath.Join(safeTmpDir, name)
	if info, err := os.Stat(srcDir); err != nil || !info.IsDir() {
		srcDir = safeTmpDir
	}
	return srcDir
}

func ensureSkillUploadTmpDir(tmpDir string) (string, error) {
	return ensureSkillUploadTmpDirInRoot(tmpDir, os.TempDir())
}

func ensureSkillUploadTmpDirInRoot(tmpDir, tempRoot string) (string, error) {
	if tmpDir == "" {
		return "", fmt.Errorf("tmp_dir is required")
	}

	absTmpDir, err := filepath.Abs(tmpDir)
	if err != nil {
		return "", fmt.Errorf("invalid tmp_dir: %w", err)
	}
	if tempRoot == "" {
		tempRoot = os.TempDir()
	}
	absSystemTmp, err := filepath.Abs(tempRoot)
	if err != nil {
		return "", fmt.Errorf("invalid system tmp dir: %w", err)
	}

	if filepath.Dir(absTmpDir) != absSystemTmp || !strings.HasPrefix(filepath.Base(absTmpDir), "skill-upload-") {
		return "", fmt.Errorf("invalid skill upload tmp_dir")
	}
	rootInfo, err := os.Lstat(absSystemTmp)
	if err != nil || rootInfo.Mode()&os.ModeSymlink != 0 || !rootInfo.IsDir() {
		return "", fmt.Errorf("invalid skill upload temp root")
	}

	info, err := os.Lstat(absTmpDir)
	if err != nil {
		return "", fmt.Errorf("invalid skill upload tmp_dir: %w", err)
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.IsDir() || !ownedByCurrentUser(info) {
		return "", fmt.Errorf("invalid skill upload tmp_dir")
	}
	if info.Mode().Perm()&0o077 != 0 {
		return "", fmt.Errorf("skill upload tmp_dir must not be group/world accessible")
	}
	return absTmpDir, nil
}

// CleanupSkillUploadTempDir removes only stale directories/files created by
// the Skill upload path.  It never follows links and never traverses unrelated
// entries in the temp volume.
func CleanupSkillUploadTempDir(root string, olderThan time.Duration) (int, error) {
	if strings.TrimSpace(root) == "" || olderThan <= 0 {
		return 0, nil
	}
	rootInfo, err := os.Lstat(root)
	if err != nil {
		if os.IsNotExist(err) {
			return 0, nil
		}
		return 0, err
	}
	if rootInfo.Mode()&os.ModeSymlink != 0 || !rootInfo.IsDir() {
		return 0, fmt.Errorf("skill temp root is not a directory")
	}
	entries, err := os.ReadDir(root)
	if err != nil {
		return 0, err
	}
	cutoff := time.Now().Add(-olderThan)
	removed := 0
	for _, entry := range entries {
		if !strings.HasPrefix(entry.Name(), "skill-upload-") && !strings.HasPrefix(entry.Name(), ".canonical-") {
			continue
		}
		path := filepath.Join(root, entry.Name())
		info, err := os.Lstat(path)
		if err != nil || info.Mode()&os.ModeSymlink != 0 || info.ModTime().After(cutoff) || !ownedByCurrentUser(info) {
			continue
		}
		if err := os.RemoveAll(path); err != nil {
			return removed, err
		}
		removed++
	}
	return removed, nil
}

func ownedByCurrentUser(info os.FileInfo) bool {
	stat, ok := info.Sys().(*syscall.Stat_t)
	if !ok {
		return true
	}
	return stat.Uid == uint32(os.Getuid())
}

func pathpkgDir(p string) string {
	dir := filepath.ToSlash(filepath.Dir(p))
	if dir == "." {
		return ""
	}
	return dir
}

// zipDir 将目录打包为可复现的 zip 字节流。
// 目录遍历顺序、时间戳和权限都显式归一化，避免同一份 Skill 因临时目录
// 或宿主机元数据不同而生成不同的对象哈希。当前接口仍返回 []byte；后续
// 按规划切换到临时文件流式打包时，应保持这里的规范化规则不变。
func zipDir(src string) ([]byte, error) {
	return zipDirWithLimit(src, MaxPackageSize)
}

func zipDirWithLimit(src string, maxPackageSize int64) ([]byte, error) {
	var buf bytes.Buffer
	if maxPackageSize <= 0 {
		maxPackageSize = MaxPackageSize
	}
	if err := zipDirToWriterContext(context.Background(), src, &limitedWriter{dst: &buf, limit: maxPackageSize}); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

type limitedWriter struct {
	dst   io.Writer
	limit int64
	n     int64
}

func (w *limitedWriter) Write(p []byte) (int, error) {
	if w.limit > 0 && w.n+int64(len(p)) > w.limit {
		remaining := w.limit - w.n
		if remaining > 0 {
			written, err := w.dst.Write(p[:remaining])
			w.n += int64(written)
			if err != nil {
				return written, err
			}
			return written, fmt.Errorf("canonical package exceeds %d bytes", w.limit)
		}
		return 0, fmt.Errorf("canonical package exceeds %d bytes", w.limit)
	}
	written, err := w.dst.Write(p)
	w.n += int64(written)
	return written, err
}

func zipDirToWriter(src string, dst io.Writer) error {
	return zipDirToWriterContext(context.Background(), src, dst)
}

func zipDirToWriterContext(ctx context.Context, src string, dst io.Writer) error {
	w := zip.NewWriter(dst)
	type fileEntry struct {
		path string
		rel  string
		mode os.FileMode
		size int64
	}
	entries := make([]fileEntry, 0)
	err := filepath.Walk(src, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return fmt.Errorf("walk error at %s: %w", path, err)
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return fmt.Errorf("symbolic links not allowed")
		}
		if info.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return fmt.Errorf("relative path error: %w", err)
		}
		rel = filepath.ToSlash(rel) // 统一正斜杠，跨平台一致
		entries = append(entries, fileEntry{path: path, rel: rel, mode: info.Mode(), size: info.Size()})
		return nil
	})
	if err != nil {
		return err
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].rel < entries[j].rel })
	if len(entries) > MaxFileCount {
		return fmt.Errorf("too many files: exceeds %d", MaxFileCount)
	}
	var totalSize int64
	for _, entry := range entries {
		if err := ctx.Err(); err != nil {
			return err
		}
		totalSize += entry.size
		if entry.size > MaxFileSize {
			return fmt.Errorf("file exceeds %dMB limit", MaxFileSize/1024/1024)
		}
		if totalSize > MaxUnpackedSize {
			return fmt.Errorf("total size exceeds %dMB", MaxUnpackedSize/1024/1024)
		}
		header := &zip.FileHeader{Name: entry.rel, Method: zip.Deflate}
		// ZIP DOS timestamps cannot represent Unix epoch; archive/zip clamps
		// this value consistently, which is still deterministic across hosts.
		header.SetModTime(time.Unix(0, 0).UTC())
		if entry.mode.Perm()&0o111 != 0 {
			header.SetMode(0o755)
		} else {
			header.SetMode(0o644)
		}
		f, err := w.CreateHeader(header)
		if err != nil {
			return err
		}
		in, err := os.Open(entry.path)
		if err != nil {
			return err
		}
		_, err = io.Copy(f, contextReader{ctx: ctx, reader: in})
		closeErr := in.Close()
		if err != nil {
			return err
		}
		if closeErr != nil {
			return closeErr
		}
	}
	if err := w.Close(); err != nil {
		return err
	}
	return nil
}
